src/Entity/Answer.php
<?php

namespace App\Entity;

use App\Repository\AnswerRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use http\Exception\InvalidArgumentException;

/**
 * @ORM\Entity(repositoryClass=AnswerRepository::class)
 */
class Answer
{
    const STATUS_NEEDS_APPROVAL = 'needs_approval';
    const STATUS_APPROVED = 'approved';
    const STATUS_SPAM = 'spam';

    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $status = self::STATUS_NEEDS_APPROVAL;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function getQuestionText(): string
    {
        if (!$this->getQuestion()) {
            return '';
        }

        return (string) $this->getQuestion()->getQuestion();
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if (!in_array($status, [self::STATUS_NEEDS_APPROVAL, self::STATUS_APPROVED, self::STATUS_SPAM])) {
            throw new InvalidArgumentException(sprintf('Invalid status %s', $status));
        }

        $this->status = $status;

        return $this;
    }

    public function isApproved(): bool
    {
        return $this->status === self::STATUS_APPROVED;
    }
}

templates/answer/_answer.html.twig
<li class="mb-4">
    {% if showQuestion|default(false) %}
        <a
                href="{{ path('app_question_show', {
                    slug: answer.question.slug
                }) }}"
                class="mb-1 link-secondary"
        >
            <strong>Question:</strong>
            {{ answer.questionText|u.truncate(80, '...') }}
        </a>
    {% endif %}
    <div class="d-flex justify-content-center">
        <div class="mr-2 pt-2">
            <img src="{{ asset('images/tisha.png') }}" width="50" height="50" alt="Tisha avatar">
        </div>
        <div class="mr-3 pt-2">
            {{ answer.content|parse_markdown }}
            <p>-- {{ answer.username }}</p>
        </div>
        <div class="mr-1 pt-1">
            <small>{{ answer.createdAt|ago }}</small>
        </div>
        <div class="vote-arrows flex-fill pt-2 js-vote-arrows" style="min-width: 90px;">
            <button class="vote-up btn btn-link" name="direction" value="up" data-category="{{ answer.id }}"><i class="far fa-arrow-alt-circle-up"></i></button>
            <button class="vote-down btn btn-link" name="direction" value="down" data-category="{{ answer.id }}"><i class="far fa-arrow-alt-circle-down"></i></button>
            <span>+ <span class="js-vote-total">{{ answer.votes }}</span></span>
        </div>
    </div>
</li>

templates/answer/pupularAnswers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Popular Answers{% endblock %}

{% block body %}
    <div class="container my-md-4">
        <div class="row">
            <ul class="list-unstyled">
                {% for answer in answers %}
                    {{ include('answer/_answer.html.twig', {
                        showQuestion: true
                    })}}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}